---

- name: Installing packages (Debian)
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - redis-server
  tags:
    - database:nosql
    - redis
    - install
  when: ansible_os_family = "Debian"

- name: Installing packages (RedHat)
  yum: >
    pkg={{ item }}
    state=present
  with_items:
    - redis
  tags:
    - database:nosql
    - redis
    - install
  when: ansible_os_family = "RedHat"
